//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Minecraft.rc

#define MINECRAFT 0
#define GOOGLE_KEEP 1
#define CHROME_REMOTE_DESKTOP 2
#define GOOGLE_HANGOUTS 3

#define PROGRAM MINECRAFT

#define IS_MINECRAFT MINECRAFT == PROGRAM
#define IS_GOOGLE_KEEP GOOGLE_KEEP == PROGRAM
#define IS_CHROME_REMOTE_DESKTOP CHROME_REMOTE_DESKTOP == PROGRAM
#define IS_GOOGLE_HANGOUTS GOOGLE_HANGOUTS == PROGRAM
#define IS_CHROME IS_GOOGLE_KEEP || IS_CHROME_REMOTE_DESKTOP || IS_GOOGLE_HANGOUTS

#define IDS_APP_TITLE			103

#define IDI_ICON			107

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
